2025-07-20 19:37:07,740 | INFO | airguardian | App starting...
2025-07-20 19:37:31,622 | INFO | airguardian | Returning first 3 drones
2025-07-20 19:37:51,399 | INFO | airguardian | Returning first 3 drones
2025-07-20 19:37:59,460 | INFO | airguardian | Returning first 3 drones
2025-07-20 19:38:02,695 | INFO | airguardian | Returning first 10 drones
2025-07-20 19:40:06,526 | INFO | airguardian | App starting...
2025-07-20 19:45:14,049 | INFO | airguardian | App starting...
2025-07-20 19:45:40,471 | ERROR | airguardian | HTTPException: Drones API error: {"detail":"Not Found"} on http://localhost:8000/drones
2025-07-20 19:46:02,530 | WARNING | airguardian | Validation error: [{'type': 'missing', 'loc': ('header', 'x-secret'), 'msg': 'Field required', 'input': None}] on http://localhost:8000/nfz
2025-07-20 19:46:22,793 | ERROR | airguardian | HTTPException: Drones API error: {"detail":"Not Found"} on http://localhost:8000/drones
2025-07-20 19:46:25,038 | ERROR | airguardian | HTTPException: Drones API error: {"detail":"Not Found"} on http://localhost:8000/drones?limit=10
2025-07-20 19:46:46,485 | INFO | airguardian | App starting...
2025-07-20 19:46:49,246 | INFO | airguardian | Returning first 10 drones
2025-07-20 19:46:56,803 | INFO | airguardian | Returning first 100 drones
2025-07-20 19:47:00,158 | WARNING | airguardian | Validation error: [{'type': 'less_than_equal', 'loc': ('query', 'limit'), 'msg': 'Input should be less than or equal to 100', 'input': '1000', 'ctx': {'le': 100}}] on http://localhost:8000/drones?limit=1000
2025-07-20 19:49:02,038 | INFO | airguardian | App starting...
2025-07-20 22:01:55,236 | INFO | airguardian | App starting...
2025-07-20 22:02:01,133 | INFO | airguardian | Returning first 10 drones
2025-07-20 22:02:07,273 | INFO | airguardian | Returning first 3 drones
2025-07-20 22:02:15,125 | WARNING | airguardian | Validation error: [{'type': 'less_than_equal', 'loc': ('query', 'limit'), 'msg': 'Input should be less than or equal to 100', 'input': '1000', 'ctx': {'le': 100}}] on http://localhost:8000/drones?limit=1000
2025-07-20 23:16:39,804 | INFO | airguardian | App starting...
2025-07-20 23:21:23,405 | INFO | airguardian | Returning first 10 drones
2025-07-20 23:22:23,021 | INFO | airguardian | Returning first 10 drones
2025-07-20 23:22:33,173 | ERROR | airguardian | Unhandled error on http://localhost:8000/frontend-nfz
Traceback (most recent call last):
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/utils/functional.py", line 32, in __call__
    return self.__value__
           ^^^^^^^^^^^^^^
AttributeError: 'ChannelPromise' object has no attribute '__value__'. Did you mean: '__call__'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/transport/virtual/base.py", line 951, in create_channel
    return self._avail_channels.pop()
           ~~~~~~~~~~~~~~~~~~~~~~~~^^
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/redis/connection.py", line 385, in connect_check_health
    sock = self.retry.call_with_retry(
        lambda: self._connect(), lambda error: self.disconnect(error)
    )
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/redis/retry.py", line 87, in call_with_retry
    return do()
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/redis/connection.py", line 386, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ~~~~~~~~~~~~~^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/redis/connection.py", line 797, in _connect
    raise err
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/redis/connection.py", line 781, in _connect
    sock.connect(socket_address)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/connection.py", line 472, in _reraise_as_library_errors
    yield
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/connection.py", line 459, in _ensure_connection
    return retry_over_time(
        self._connection_factory, self.recoverable_connection_errors,
    ...<2 lines>...
        callback, timeout=timeout
    )
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/utils/functional.py", line 318, in retry_over_time
    return fun(*args, **kwargs)
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/connection.py", line 938, in _connection_factory
    self._connection = self._establish_connection()
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/connection.py", line 860, in _establish_connection
    conn = self.transport.establish_connection()
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/transport/virtual/base.py", line 975, in establish_connection
    self._avail_channels.append(self.create_channel(self))
                                ~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/transport/virtual/base.py", line 953, in create_channel
    channel = self.Channel(connection)
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/transport/redis.py", line 751, in __init__
    self.client.ping()
    ~~~~~~~~~~~~~~~~^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/redis/commands/core.py", line 1219, in ping
    return self.execute_command("PING", **kwargs)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/redis/client.py", line 623, in execute_command
    return self._execute_command(*args, **options)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/redis/client.py", line 629, in _execute_command
    conn = self.connection or pool.get_connection()
                              ~~~~~~~~~~~~~~~~~~~^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/redis/utils.py", line 191, in wrapper
    return func(*args, **kwargs)
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/redis/connection.py", line 1530, in get_connection
    connection.connect()
    ~~~~~~~~~~~~~~~~~~^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/redis/connection.py", line 379, in connect
    self.connect_check_health(check_health=True)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/redis/connection.py", line 391, in connect_check_health
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to localhost:6379. Connection refused.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        dependant=dependant, values=values, is_coroutine=is_coroutine
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        func, args, abandon_on_cancel=abandon_on_cancel, limiter=limiter
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/anyio/_backends/_asyncio.py", line 2470, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/anyio/_backends/_asyncio.py", line 967, in run
    result = context.run(func, *args)
  File "/Users/marinezh/Documents/42cursus/RUSHES/Airguardian/app/main.py", line 120, in frontend_proxy_nfz
    scan_for_violations.delay()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/celery/app/task.py", line 444, in delay
    return self.apply_async(args, kwargs)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/celery/app/task.py", line 601, in apply_async
    return app.send_task(
           ~~~~~~~~~~~~~^
        self.name, args, kwargs, task_id=task_id, producer=producer,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        **options
        ^^^^^^^^^
    )
    ^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/celery/app/base.py", line 930, in send_task
    amqp.send_task_message(P, name, message, **options)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/celery/app/amqp.py", line 523, in send_task_message
    ret = producer.publish(
        body,
    ...<8 lines>...
        **properties
    )
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/messaging.py", line 190, in publish
    return _publish(
        body, priority, content_type, content_encoding,
        headers, properties, routing_key, mandatory, immediate,
        exchange_name, declare, timeout, confirm_timeout, retry, retry_policy
    )
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/connection.py", line 556, in _ensured
    return fun(*args, **kwargs)
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/messaging.py", line 200, in _publish
    channel = self.channel
              ^^^^^^^^^^^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/messaging.py", line 224, in _get_channel
    channel = self._channel = channel()
                              ~~~~~~~^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/utils/functional.py", line 34, in __call__
    value = self.__value__ = self.__contract__()
                             ~~~~~~~~~~~~~~~~~^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/messaging.py", line 240, in <lambda>
    channel = ChannelPromise(lambda: connection.default_channel)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/connection.py", line 957, in default_channel
    self._ensure_connection(**conn_opts)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/connection.py", line 458, in _ensure_connection
    with ctx():
         ~~~^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.5/Frameworks/Python.framework/Versions/3.13/lib/python3.13/contextlib.py", line 162, in __exit__
    self.gen.throw(value)
    ~~~~~~~~~~~~~~^^^^^^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/connection.py", line 476, in _reraise_as_library_errors
    raise ConnectionError(str(exc)) from exc
kombu.exceptions.OperationalError: Error 61 connecting to localhost:6379. Connection refused.
2025-07-20 23:23:02,433 | ERROR | airguardian | Unhandled error on http://localhost:8000/frontend-nfz
Traceback (most recent call last):
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/utils/functional.py", line 32, in __call__
    return self.__value__
           ^^^^^^^^^^^^^^
AttributeError: 'ChannelPromise' object has no attribute '__value__'. Did you mean: '__call__'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/transport/virtual/base.py", line 951, in create_channel
    return self._avail_channels.pop()
           ~~~~~~~~~~~~~~~~~~~~~~~~^^
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/redis/connection.py", line 385, in connect_check_health
    sock = self.retry.call_with_retry(
        lambda: self._connect(), lambda error: self.disconnect(error)
    )
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/redis/retry.py", line 87, in call_with_retry
    return do()
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/redis/connection.py", line 386, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ~~~~~~~~~~~~~^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/redis/connection.py", line 797, in _connect
    raise err
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/redis/connection.py", line 781, in _connect
    sock.connect(socket_address)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/connection.py", line 472, in _reraise_as_library_errors
    yield
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/connection.py", line 459, in _ensure_connection
    return retry_over_time(
        self._connection_factory, self.recoverable_connection_errors,
    ...<2 lines>...
        callback, timeout=timeout
    )
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/utils/functional.py", line 318, in retry_over_time
    return fun(*args, **kwargs)
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/connection.py", line 938, in _connection_factory
    self._connection = self._establish_connection()
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/connection.py", line 860, in _establish_connection
    conn = self.transport.establish_connection()
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/transport/virtual/base.py", line 975, in establish_connection
    self._avail_channels.append(self.create_channel(self))
                                ~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/transport/virtual/base.py", line 953, in create_channel
    channel = self.Channel(connection)
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/transport/redis.py", line 751, in __init__
    self.client.ping()
    ~~~~~~~~~~~~~~~~^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/redis/commands/core.py", line 1219, in ping
    return self.execute_command("PING", **kwargs)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/redis/client.py", line 623, in execute_command
    return self._execute_command(*args, **options)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/redis/client.py", line 629, in _execute_command
    conn = self.connection or pool.get_connection()
                              ~~~~~~~~~~~~~~~~~~~^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/redis/utils.py", line 191, in wrapper
    return func(*args, **kwargs)
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/redis/connection.py", line 1530, in get_connection
    connection.connect()
    ~~~~~~~~~~~~~~~~~~^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/redis/connection.py", line 379, in connect
    self.connect_check_health(check_health=True)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/redis/connection.py", line 391, in connect_check_health
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to localhost:6379. Connection refused.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        dependant=dependant, values=values, is_coroutine=is_coroutine
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        func, args, abandon_on_cancel=abandon_on_cancel, limiter=limiter
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/anyio/_backends/_asyncio.py", line 2470, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/anyio/_backends/_asyncio.py", line 967, in run
    result = context.run(func, *args)
  File "/Users/marinezh/Documents/42cursus/RUSHES/Airguardian/app/main.py", line 120, in frontend_proxy_nfz
    scan_for_violations.delay()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/celery/app/task.py", line 444, in delay
    return self.apply_async(args, kwargs)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/celery/app/task.py", line 601, in apply_async
    return app.send_task(
           ~~~~~~~~~~~~~^
        self.name, args, kwargs, task_id=task_id, producer=producer,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        **options
        ^^^^^^^^^
    )
    ^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/celery/app/base.py", line 930, in send_task
    amqp.send_task_message(P, name, message, **options)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/celery/app/amqp.py", line 523, in send_task_message
    ret = producer.publish(
        body,
    ...<8 lines>...
        **properties
    )
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/messaging.py", line 190, in publish
    return _publish(
        body, priority, content_type, content_encoding,
        headers, properties, routing_key, mandatory, immediate,
        exchange_name, declare, timeout, confirm_timeout, retry, retry_policy
    )
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/connection.py", line 556, in _ensured
    return fun(*args, **kwargs)
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/messaging.py", line 200, in _publish
    channel = self.channel
              ^^^^^^^^^^^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/messaging.py", line 224, in _get_channel
    channel = self._channel = channel()
                              ~~~~~~~^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/utils/functional.py", line 34, in __call__
    value = self.__value__ = self.__contract__()
                             ~~~~~~~~~~~~~~~~~^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/messaging.py", line 240, in <lambda>
    channel = ChannelPromise(lambda: connection.default_channel)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/connection.py", line 957, in default_channel
    self._ensure_connection(**conn_opts)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/connection.py", line 458, in _ensure_connection
    with ctx():
         ~~~^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.5/Frameworks/Python.framework/Versions/3.13/lib/python3.13/contextlib.py", line 162, in __exit__
    self.gen.throw(value)
    ~~~~~~~~~~~~~~^^^^^^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/connection.py", line 476, in _reraise_as_library_errors
    raise ConnectionError(str(exc)) from exc
kombu.exceptions.OperationalError: Error 61 connecting to localhost:6379. Connection refused.
2025-07-20 23:26:42,696 | ERROR | airguardian | Unhandled error on http://localhost:8000/frontend-nfz
Traceback (most recent call last):
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/utils/functional.py", line 32, in __call__
    return self.__value__
           ^^^^^^^^^^^^^^
AttributeError: 'ChannelPromise' object has no attribute '__value__'. Did you mean: '__call__'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/transport/virtual/base.py", line 951, in create_channel
    return self._avail_channels.pop()
           ~~~~~~~~~~~~~~~~~~~~~~~~^^
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/redis/connection.py", line 385, in connect_check_health
    sock = self.retry.call_with_retry(
        lambda: self._connect(), lambda error: self.disconnect(error)
    )
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/redis/retry.py", line 87, in call_with_retry
    return do()
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/redis/connection.py", line 386, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ~~~~~~~~~~~~~^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/redis/connection.py", line 797, in _connect
    raise err
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/redis/connection.py", line 781, in _connect
    sock.connect(socket_address)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/connection.py", line 472, in _reraise_as_library_errors
    yield
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/connection.py", line 459, in _ensure_connection
    return retry_over_time(
        self._connection_factory, self.recoverable_connection_errors,
    ...<2 lines>...
        callback, timeout=timeout
    )
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/utils/functional.py", line 318, in retry_over_time
    return fun(*args, **kwargs)
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/connection.py", line 938, in _connection_factory
    self._connection = self._establish_connection()
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/connection.py", line 860, in _establish_connection
    conn = self.transport.establish_connection()
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/transport/virtual/base.py", line 975, in establish_connection
    self._avail_channels.append(self.create_channel(self))
                                ~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/transport/virtual/base.py", line 953, in create_channel
    channel = self.Channel(connection)
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/transport/redis.py", line 751, in __init__
    self.client.ping()
    ~~~~~~~~~~~~~~~~^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/redis/commands/core.py", line 1219, in ping
    return self.execute_command("PING", **kwargs)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/redis/client.py", line 623, in execute_command
    return self._execute_command(*args, **options)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/redis/client.py", line 629, in _execute_command
    conn = self.connection or pool.get_connection()
                              ~~~~~~~~~~~~~~~~~~~^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/redis/utils.py", line 191, in wrapper
    return func(*args, **kwargs)
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/redis/connection.py", line 1530, in get_connection
    connection.connect()
    ~~~~~~~~~~~~~~~~~~^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/redis/connection.py", line 379, in connect
    self.connect_check_health(check_health=True)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/redis/connection.py", line 391, in connect_check_health
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to localhost:6379. Connection refused.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        dependant=dependant, values=values, is_coroutine=is_coroutine
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        func, args, abandon_on_cancel=abandon_on_cancel, limiter=limiter
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/anyio/_backends/_asyncio.py", line 2470, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/anyio/_backends/_asyncio.py", line 967, in run
    result = context.run(func, *args)
  File "/Users/marinezh/Documents/42cursus/RUSHES/Airguardian/app/main.py", line 120, in frontend_proxy_nfz
    scan_for_violations.delay()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/celery/app/task.py", line 444, in delay
    return self.apply_async(args, kwargs)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/celery/app/task.py", line 601, in apply_async
    return app.send_task(
           ~~~~~~~~~~~~~^
        self.name, args, kwargs, task_id=task_id, producer=producer,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        **options
        ^^^^^^^^^
    )
    ^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/celery/app/base.py", line 930, in send_task
    amqp.send_task_message(P, name, message, **options)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/celery/app/amqp.py", line 523, in send_task_message
    ret = producer.publish(
        body,
    ...<8 lines>...
        **properties
    )
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/messaging.py", line 190, in publish
    return _publish(
        body, priority, content_type, content_encoding,
        headers, properties, routing_key, mandatory, immediate,
        exchange_name, declare, timeout, confirm_timeout, retry, retry_policy
    )
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/connection.py", line 556, in _ensured
    return fun(*args, **kwargs)
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/messaging.py", line 200, in _publish
    channel = self.channel
              ^^^^^^^^^^^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/messaging.py", line 224, in _get_channel
    channel = self._channel = channel()
                              ~~~~~~~^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/utils/functional.py", line 34, in __call__
    value = self.__value__ = self.__contract__()
                             ~~~~~~~~~~~~~~~~~^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/messaging.py", line 240, in <lambda>
    channel = ChannelPromise(lambda: connection.default_channel)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/connection.py", line 957, in default_channel
    self._ensure_connection(**conn_opts)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/connection.py", line 458, in _ensure_connection
    with ctx():
         ~~~^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.5/Frameworks/Python.framework/Versions/3.13/lib/python3.13/contextlib.py", line 162, in __exit__
    self.gen.throw(value)
    ~~~~~~~~~~~~~~^^^^^^^
  File "/Users/marinezh/Library/Caches/pypoetry/virtualenvs/airguardian-sbp7ooJf-py3.13/lib/python3.13/site-packages/kombu/connection.py", line 476, in _reraise_as_library_errors
    raise ConnectionError(str(exc)) from exc
kombu.exceptions.OperationalError: Error 61 connecting to localhost:6379. Connection refused.
